language: c

os: linux

compiler:
    - clang
    - gcc

script:
    - git ls-files src/*.c src/*.h test/*.c | xargs clang-format -i && git diff --exit-code
    - make test
    - ./bin/test
    - make

dist: xenial
